### ISSUE TITLE
Issues with field selection

### ISSUE THREAD

**Issue by learnbyexample** [sstadick/hck#30]
1) Specifying a field number multiple times is not working for some cases:

```bash
# shouldn't print 4th field, expected output is '3,1'
$ echo '1,2,3,4,5' | hck -d, -f3,1,3 -D,
3,1,4

# sometimes it causes this error
$ echo '1,2,3,4,5' | hck -d, -f3,3,1,2 -D,
thread 'main' panicked at 'internal error: entered unreachable code'
```

2) Output order changes sometimes when some fields are specified multiple times. Not sure if this is related to the previous issue.

```bash
# works as expected
$ printf '1 2 3 4 5\na b c d e\n' | hck -f2-3,5,1 -D,
2,3,5,1
b,c,e,a

# adding 2-4 is causing 5th field to be displayed at the end instead of middle
$ printf '1 2 3 4 5\na b c d e\n' | hck -f2-3,5,1,2-4 -D,
2,3,1,4,5
b,c,a,d,e
```

3) Not sure how the output fields are ordered when both `-f` and `-F` options are used.

```bash
# same order as -f and -F options
$ printf 'a,b,c,d,e\n1,2,3,4,5\n' | hck -d, -D: -f3 -F 'd' -F 'a'
c:d:a
3:4:1

# different order
$ printf 'a,b,c,d,e\n1,2,3,4,5\n' | hck -d, -D: -f3 -F 'b' -F 'a'
b:c:a
2:3:1
$ printf 'a,b,c,d,e\n1,2,3,4,5\n' | hck -d, -D: -f3 -F 'a'
a:c
1:3
```

**Comment by sstadick** [comment]
Thank you again for the awesome bug descriptions! Pleas re-open if the latest version doesn't fix it for you. 

Issues 1 and 2 should be fixed in v0.5.4 which is building now.

See https://github.com/sstadick/hck#splitting-by-index-and-by-header for an explainer of what is happening when mixing by-index and by-header selection.
